scene_0:
  name: "warehouse"
  render_offset: [0, 0, 0]

scene_1:
  name: "street"
  render_offset: [0, 0, 0]

scene_2:
  name: "forest"
  render_offset: [78, 66.5, 114.48]

scene_3:
  name: "wasteland"
  render_offset: [1140, 1026, 108]