scene_0:
  name: "warehouse"
  render_offset: [0, 0, 0]

scene_1:
  name: "industrial"
  render_offset: [0, 0, 0]

scene_2:
  name: "forest"
  render_offset: [98.0, 18.0, 0.05]

scene_3:
  name: "wasteland"
  render_offset: [1140, 1026, 108]